workflow file

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -26,4 +26,35 @@ jobs:
         uses: actions/checkout@v4
       - name: Check coverage
         run: |
-          
+          if [ ! -f ./coverage/coverage-summary.json ]; then
+          echo "No coverage report"
+          exit 1
+          fi
+          COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
+          echo "Coverage is ${COVERAGE}%"
+          if (( $(echo "$COVERAGE < 90%" | bc -1) )); then
+          echo "Coverage below threshold, deployment aborted"
+          exit 1
+          fi
+  deploy:
+    runs-on: ubuntu-latest
+    needs: check-coverage
+    permissions:
+      contents: read
+      pages: write
+      id-token: write
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install dependencies
+        run: npm install
+      - name: Build dist
+        run: npm run build
+      - name: Set up Pages
+        uses: actions/configure-pages@v3
+      - name: Upload dist
+        uses: actions/upload-pages-artifact@v1
+        with:
+          path: "./dist"
+      - name: Deploy to Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
